services:
  - type: web
    name: pizarron-v11
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true